version: '3'
services:
  mongodb:
    image: "centos/mongodb-32-centos7"
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DBNAME}
      MONGODB_ADMIN_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
    ports:
      - "27017:27017"

  rpc_server_storage:
    image: yoyonel/pyconfr_2019_grpc_nlp_server_storage
    ports:
     - "50052:50052"
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_SERVICE_HOST: mongodb
    entrypoint: pyconfr_2019_grpc_nlp_server_storage
    depends_on:
      - mongodb

  # rpc_server_features:
  #   image: ${DOCKER_TAG}
  #   ports:
  #     - "50051:50051"
  #   environment:
  #     MONGODB_USER: ${MONGODB_USER}
  #     MONGODB_PASSWORD: ${MONGODB_PASSWORD}
  #     MONGODB_SERVICE_HOST: mongodb
  #   entrypoint: twitter_analyzer_rpc_features_server
  #   depends_on:
  #     - mongodb